### ISSUE TITLE
Prefer Readonly<T> over readonly keyword

### ISSUE THREAD

**Issue by RebeccaStevens** [eslint-functional/eslint-plugin-functional#32]
Transferred from jonaskello/tslint-immutable#58

**Comment by RebeccaStevens** [comment]
This enhancement will most likely require quite a few new tests; #31 probably needs to be sorted out beforehand.

**Comment by jonaskello** [comment]
I think we should keep the rule to check for `readonly` attributes but we could add this somehow as an option or separate rule. Since it would be an addition it would not require a major version increment so we could probably look into it post 1.0.0.

**Comment by RebeccaStevens** [comment]
I can think of two ways to go about this:

**Option 1**
Add an option to the `prefer-readonly-type` rule called something like `style` with options `keyword` (default) and `generic` (maybe also `either`/`any`?).

**Option 2**
Create a new rule to enforce one style over the other
