### ISSUE TITLE
Autofix on TypeScript mapped types with `-readonly` cause syntax error

### ISSUE THREAD

**Issue by maxxxxxdlp** [eslint-functional/eslint-plugin-functional#384]
# Bug Report

I have the following code:

```ts
export type Writable<T> = {
  -readonly [K in keyof T]: T[K];
};
```

ESLint reports "functional/prefer-readonly-type" rule and an option to "--fix" it.

## Expected behavior

Autofix should remove `-`:

```ts
export type Writable<T> = {
  readonly [K in keyof T]: T[K];
};
```

## Actual behavior

Autofix creates a syntax error:

```ts
export type Writable<T> = { readonly
  -readonly [K in keyof T]: T[K];
};
```

## Steps to reproduce

ESLint config:

```json5
{
  // ...
  plugins: [
    // ...
    'functional',
    // ...
  ],
  extends: [
    // ...
    "plugin:functional/external-recommended",
    "plugin:functional/recommended",
    "plugin:functional/no-object-orientation",
    "plugin:functional/no-statements",
    "plugin:functional/no-exceptions",
    "plugin:functional/currying",
    "plugin:functional/stylistic",
    // ...
  ],
// ...
}
```

## Proposed changes

Either disable autofix for `-readonly`, or hande it properly.

See https://github.com/microsoft/TypeScript/pull/21919

**Comment by RebeccaStevens** [comment]
I believe the correct behavior should be for it to not try and auto fix this at all.
