### ISSUE TITLE
[prefer-tacit] should not consider as error when the user intentionally skipped some parameters

### ISSUE THREAD

**Issue by foray1010** [eslint-functional/eslint-plugin-functional#486]
# Bug Report

test.ts:

```ts
const a = ['1', '2']
a.map((x) => parseInt(x))
// result: [1, 2]
```

## Expected behavior

No eslint error

## Actual behavior

`prefer-tacit` error, and autofixed to the following code which does not work because parseInt takes a second parameter `radix` and it should not be an `index`

test.ts:

```ts
const a = ['1', '2']
a.map(parseInt)
// result: [1, NaN]
```

## Steps to reproduce

Code mentioned above, running in eslint-plugin-functional `v4.4.0` with rule `'functional/prefer-tacit': 'error'`

## Proposed changes

Do not consider it as error when the user intentionally skipped some parameters

**Comment by RebeccaStevens** [comment]
Yeah, that shouldn't be happening, and I thought there were checks in place to make sure it doesn't.

Can I confirm with you that you are use TypeScript and don't have `assumeTypes.allowFixer` enabled?

**Comment by foray1010** [comment]
@RebeccaStevens yup, I am using TS and the rule is `'functional/prefer-tacit': 'error'` - I presume it means `assumeTypes.allowFixer` is not enabled

**Comment by RebeccaStevens** [comment]
Alright, I'll look into it.

**Comment by RebeccaStevens** [comment]
Hmmm, strange. I can reproduce the error with `parseInt` but not with `Number.parseInt`.
