### ISSUE TITLE
[prefer-readonly-type] Support Readonly<T>

### ISSUE THREAD

**Issue by ulrichb** [eslint-functional/eslint-plugin-functional#51]
Support the following case (at the moment `functional/prefer-readonly-type` gets emitted):

```TS
type MyType = Readonly<{ a: string, b: number }>;
```

This is a prerequisite for #32 (which is about a fixer to `Readonly<T>` if I understand it correctly); but the validation can implemented before.

**Comment by kevinbarabash** [comment]
I'm interested in taking this on.

**Comment by RebeccaStevens** [comment]
@kevinbarabash it's yours 😄.

I think the way to go about it is to add an option to the `prefer-readonly-type` rule called something like `style` with options `keyword` (default) and `generic` .

**Comment by kevinbarabash** [comment]
Thanks.  I'll start work on this this weekend.

**Comment by RebeccaStevens** [comment]
@kevinbarabash How you going with this?

**Comment by kevinbarabash** [comment]
I ended up getting side-tracked by something else and have put my TypeScript development on hold.

**Comment by JacksonGariety** [comment]
+1 for this. Having to put the `readonly` modifier before every single key decreases readability. And this rule is critical.

**Comment by safareli** [comment]
+1

**Comment by adrian-gierakowski** [comment]
Just wanted to point out that https://typescript-eslint.io/rules/prefer-readonly-parameter-types works with `Readonly` as well as `ReadonlyDeep` from https://github.com/sindresorhus/type-fest, so maybe we could borrow from it's implementation

**Comment by RebeccaStevens** [comment]
@adrian-gierakowski I've actually been working over there helping with that rule. I've also since extracted out the relevant bits and improved upon them in a new lib called [is-immutable-type](https://www.npmjs.com/package/is-immutable-type). v5 of this lib (currently in beta) uses that library and resolves this issue.
