### ISSUE TITLE
[type-declaration-immutability] add support for union types when they are interfaces

### ISSUE THREAD

**Issue by m4thieulavoie** [eslint-functional/eslint-plugin-functional#529]
## Bug Report

**eslint config:**

```
'functional/type-declaration-immutability': [
          'error',
          {
            rules: [
              {
                identifiers: '^(?!I?Mutable).+',
                immutability: 'ReadonlyShallow',
                comparator: 'AtLeast',
                fixer: false,
              },
            ],
            ignoreInterfaces: true,
          },
        ],
```

Given the above config, I'm basically wanting anything to be at least `ReadonlyShallow` except for `interface`s, which works great. However, given this example

```
interface A {
  prop: string;
}

interface B {
  prop2: string;
}

type UnionedType = A | B;
```

I'm getting the following error

```
This type is declare to have an immutability of at least "ReadonlyShallow" (actual: "Mutable")
```

I don't _think_ that my config is off. It seems to me like this is more of a cornercase for this new rule.

### Expected behavior

Union type of > 1 interfaces doesn't error out if `ignoreInterfaces` is `true`

### Actual behavior

Union type of > 1 interfaces errors out if `ignoreInterfaces` is `true`

### Steps to reproduce

Add above config and use above example

**Comment by RebeccaStevens** [comment]
I've been thinking about this proposal quite a bit, but I think ultimately, this not something I want to implement into the rule.

As an alternative, you can use a naming convention.
For example, you could prefix such types with `IU` (short for "interface union") and then ignore this pattern with: `"ignorePattern": "^IU[A-Z]\\S+"`

**Comment by m4thieulavoie** [comment]
> I've been thinking about this proposal quite a bit, but I think ultimately, this not something I want to implement into the rule.
> 
> As an alternative, you can use a naming convention. For example, you could prefix such types with `IU` (short for "interface union") and then ignore this pattern with: `"ignorePattern": "^IU[A-Z]\\S+"`

Unfortunately that would require us renaming thousands of union `type`s. I think we won't be able to leverage this rule on our project for the time being 😢

**Comment by RebeccaStevens** [comment]
You could use this rule in an op-in way.

If you use a config similar to the [override for the `recommended` and `lite` presets](https://github.com/eslint-functional/eslint-plugin-functional/blob/main/docs/rules/type-declaration-immutability.md#recommended-and-lite), you'll need to prefix type declarations with `Readonly` for the rule to enforce they are readonly.
