### ISSUE TITLE
`functional/functional-parameters` Limit only to specific types

### ISSUE THREAD

**Issue by danielnixon** [eslint-functional/eslint-plugin-functional#575]
## Suggestion

When using `functional/functional-parameters`, we have [`ignorePrefixSelector`](https://github.com/eslint-functional/eslint-plugin-functional/blob/main/docs/rules/functional-parameters.md#ignoreprefixselector) but that can't tap into TypeScript type information.

There are a few places that I would love to whitelist in a way that requires type information. It would be great if we had that ability.

Here's one motivating example:

In https://github.com/gcanti/fp-ts, there are many cases where Lazy thunks are used to achieve functional purity.

One case is when lifting `Promise`s (eager, not referentially transparent) into fp-ts `TaskEither`s (lazy, referentially transparent):

```ts
export declare const tryCatch: <E, A>(f: Lazy<Promise<A>>, onRejected: (reason: unknown) => E) => TaskEither<E, A>
```

When calling that, you are frequently taking some existing code that returns a `Promise` and doing this to it:

```ts
TE.tryCatch(() => existingCodeThatReturnsPromise);
```

That lazy thunk (`() => ...`) unfortunately triggers `functional/functional-parameters`, even though in this case we're writing code that in spirit is extremely functional.

Luckily, fp-ts defines `Lazy` like so:

```ts
export interface Lazy<A> {
  (): A
}
```

It could have defined it like `export type Lazy<A> = () => A;`, but for our purposes here we're lucky they made it a named interface.

If we could tap into the type information, we'd know that the contextual type of `() => existingCodeThatReturnsPromise` is actually `Lazy<...>` due to it being passed to `TE.tryCatch` (first param type being: `f: Lazy<Promise<A>>`). That would allow us to whitelist cases like this.

Note that fp-ts also defines a type `IO<A>` that is structurally the same as `Lazy<A>` but has different semantics: `IO<A>` is assumed to be impure. We would not want to whitelist IOs.

**Comment by danielnixon** [comment]
Very related: https://github.com/RebeccaStevens/is-immutable-type/issues/47#issuecomment-1467675776

**Comment by RebeccaStevens** [comment]
What sort of change would you like to see for this? A new option? How do you think it should work?

Note: we already have `ignoreLambdaExpression`, a sub-option of `enforceParameterCount`.

**Comment by danielnixon** [comment]
Thanks for asking @RebeccaStevens. I'm picturing an ability to override the rule using something _like_ https://github.com/RebeccaStevens/is-immutable-type#overrides, so something like this:

```js
[{ type: { from: "fp-ts", name: "Lazy" }}]
```

That would be the most 'surgical' override. It would allow ESLint to continue to flag lambdas in the general case (no need for ignoreLambdaExpression) while permitting us to use them whenever they're used to achieve laziness with fp-ts, such as via

```ts
TE.tryCatch(() => existingCodeThatReturnsPromise);
```

I understand if you think this is more trouble than its worth and your recommendation is to just use ignoreLambdaExpression.
