### ISSUE TITLE
Support for TypeScript 5.x

### ISSUE THREAD

**Issue by DiggesT** [eslint-functional/eslint-plugin-functional#613]
## Bug Report

Eslint-plugin-functional support only 4.x version of typescript.

### Expected behavior

No conflicts running `npm install` with typescript 5.x verxion.

### Actual behavior

Console error:
``` console
npm ERR! Found: typescript@5.0.2
npm ERR! node_modules/typescript
npm ERR!   typescript@"^5.0.2" from the root project
npm ERR!   peerOptional typescript@">=4.0.2" from eslint-plugin-functional@5.0.6
npm ERR!   node_modules/eslint-plugin-functional
npm ERR!     dev eslint-plugin-functional@"^5.0.6" from the root project
npm ERR!   4 more (fork-ts-checker-webpack-plugin, is-immutable-type, ...)
npm ERR! 
```
### Steps to reproduce

1. use `eslint-plugin-functional@5.0.6`
2. use `typescript@5.x`
3. run `npm install`

**Comment by RebeccaStevens** [comment]
I can't recreate this error.

TypeScript 5 should just work with this plugin.
In our `package.json` file, we specify that typescript >=4.0.2 is required as an optional peer dependency, and typescript@5.0.2 meets this requirement.

Maybe the issue you are having is with one of the other packages you are using. If you still think this plugin is responsible, could you please provide a minimal repo example?

**Comment by DiggesT** [comment]
My bad, you are right, it's work correctly. The problem was in `react-scripts` that i used together with `eslint-plugin-functional`.

``` console
npm ERR! Could not resolve dependency:
npm ERR! peerOptional typescript@"^3.2.1 || ^4" from react-scripts@5.0.1
npm ERR! node_modules/react-scripts
npm ERR!   react-scripts@"^5.0.1" from the root project
npm ERR!   peer react-scripts@"*" from @craco/craco@5.9.0
npm ERR!   node_modules/@craco/craco
npm ERR!     @craco/craco@"^5.5.0" from craco@0.0.3
npm ERR!     node_modules/craco
npm ERR!       craco@"^0.0.3" from the root project
```
