### ISSUE TITLE
`prefer-immutable-types` How to require readonly on the class variable's type, but not the property field?

### ISSUE THREAD

**Issue by foray1010** [eslint-functional/eslint-plugin-functional#635]
I want to combine `prefer-immutable-types` with `@typescript-eslint/prefer-readonly`, so that I can keep all `public` and `protected` fields mutable but keep the data type immutable. But now seems `prefer-immutable-types`'s `variables` setting apply to both the field immutability and also the variable type, and the `ignoreClasses: "fieldsOnly"` setting will turn off both. Is it possible to handle them separately? Thank you!

**Comment by RebeccaStevens** [comment]
Could you give a code example of what you would like to be able to do?
