### ISSUE TITLE
FYI: typescript-eslint@v6 will remove parserServices.hasFullTypeInformation

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint-functional/eslint-plugin-functional#678]
👋 Hi! I'm one of the maintainers of [typescript-eslint](https://typescript-eslint.io). We're getting ready to release a new v6 major version of the tooling, which includes some small breaking changes.

Coming over from https://github.com/typescript-eslint/typescript-eslint/issues/7124: I see this repo contains references to `hasFullTypeInformation`. That property is something we've never recommended using (see that issue & https://github.com/typescript-eslint/typescript-eslint/issues/7158). We recommend instead using `ESLintUtils.getParserServices` per https://typescript-eslint.io/developers/custom-rules#typed-rules.

If you _really_ want to "progressively enhance" lint rules, `parserServices.program` will be `null` if type information isn't available. But we definitely recommend against that kind of rule behavior changing.

Overall, I'd suggest trying out typescript-eslint@v6 and making sure internal builds & downstream repos still compile & lint nicely with all the changes. Let me know if there's anything we can do to help with the v6 upgrade! 💖

**Comment by pegak** [comment]
Hi,
I am using this rule in https://github.com/pegak/nauc-me-it and after update to v6 it fails with error:
`3:31  Error: Parameter should have an immutability of at least "ReadonlyShallow" (actual: "Unknown").  functional/prefer-immutable-types`

Could it be caused by this change?

**Comment by RebeccaStevens** [comment]
v6 isn't supported yet. I'll should be able to work on this sometime in the next week.
Theses' work that needs to be done both in repo and in https://github.com/RebeccaStevens/is-immutable-type

**Comment by pegak** [comment]
Many thanks. Can I help? :)

**Comment by RebeccaStevens** [comment]
@pegak Thanks for the offer, but I should be good. I've already done the majority of the work back when v6 was in beta. I just need to finish it. I'm starting back on it now.

**Comment by RebeccaStevens** [comment]
[6.0.0-next.1](https://github.com/eslint-functional/eslint-plugin-functional/pull/683/commits/a56d30311ecbff475110fede716a08c65c4dc95b) is now available for testing.
