### ISSUE TITLE
mutated array/object declared with const errors but ok with let 

### ISSUE THREAD

**Issue by rickmed** [eslint-functional/eslint-plugin-functional#691]
## Suggestion

Is there a setting where, if you declare an array or object with const and mutate it, it errors, but if declared with let it's ok?

I've been searching through the docs but couldn't figure out.

PS: I'm using typescript.

**Comment by RebeccaStevens** [comment]
No, we don't have a rule like that.

What I personally use is the [`naming-convention`](https://typescript-eslint.io/rules/naming-convention/) rule to enforce variables declared with `let` are prefixed with `m_` (for mutable). Then I use [`immutable-data`'s `ignoreAccessorPattern`](https://github.com/eslint-functional/eslint-plugin-functional/blob/main/docs/rules/immutable-data.md#ignoreaccessorpattern) to ignore such variables.

I'm not sure if I'd be in favor of adding your suggestion a built-in option or not. I'd need to think about the flow on effects of such an option.

**Comment by rickmed** [comment]
I think it's worth giving it a good thought.

**Comment by rickmed** [comment]
Is there a way to use ignore patterns or something to make all arrays immutable by default but using some regex in the identifier to make it mutable like "let/const mut_arr = []"?

**Comment by RebeccaStevens** [comment]
> Is there a way to use ignore patterns or something to make all arrays immutable by default but using some regex in the identifier to allow mutations like "let/const mut_arr = []"?

I'm not sure what you mean exactly. `ignorePattern` will let you match against the variable name (e.g. `mut_arr`); if it matches then the rule won't report any issues. Any mutations on objects and arrays will be reported so in that sense they are already all immutable by default.

**Comment by RebeccaStevens** [comment]
> So let's say I have a class (or object). Is there any way to do this?
> 
> ```ts
> class Hey {
>     mut_array = []
> }
> 
> const hey = new Hey()
> 
> hey.mut_array.push(1)   // currently, it complains with "Modifying an array is not allowed."
> ```

You can use the [`ignoreAccessorPattern` option](https://github.com/eslint-functional/eslint-plugin-functional/blob/main/docs/rules/immutable-data.md#ignoreaccessorpattern) for this.

This should do what you want:

```jsonc
{
  "ignoreAccessorPattern": "**.mut_*.**"
}
```
